### ISSUE TITLE
error with last backend version

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus-frontend#58]
i moved the elog-backend to use the new library, the test passed all but the UI has this problem, can you help me what is the problem?
```
index-8646652c.js:40 RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at xh (index-8646652c.js:84:6147)
    at index-8646652c.js:136:23968
    at Fm (index-8646652c.js:38:19518)
    at Kv (index-8646652c.js:40:1571)
    at Iw (index-8646652c.js:40:45998)
    at _w (index-8646652c.js:40:39763)
    at wC (index-8646652c.js:40:39691)
    at Cu (index-8646652c.js:40:39545)
    at th (index-8646652c.js:40:35913)
Hd @ index-8646652c.js:40
a.componentDidCatch.n.callback @ index-8646652c.js:40
Fv @ index-8646652c.js:38
tg @ index-8646652c.js:40
Lw @ index-8646652c.js:40
vC @ index-8646652c.js:40
xC @ index-8646652c.js:40
wo @ index-8646652c.js:40
og @ index-8646652c.js:40
vo @ index-8646652c.js:38
(anonymous) @ index-8646652c.js:40
setTimeout (async)
(anonymous) @ index-8646652c.js:68
ub @ index-8646652c.js:68
Mg @ index-8646652c.js:68
l @ index-8646652c.js:68
o @ index-8646652c.js:68
dispatch @ index-8646652c.js:68
setData @ index-8646652c.js:68
onSuccess @ index-8646652c.js:68
h @ index-8646652c.js:68
Promise.then (async)
g @ index-8646652c.js:68
fb @ index-8646652c.js:68
fetch @ index-8646652c.js:68
executeFetch @ index-8646652c.js:68
onSubscribe @ index-8646652c.js:68
subscribe @ index-8646652c.js:68
(anonymous) @ index-8646652c.js:76
ew @ index-8646652c.js:38
sc @ index-8646652c.js:40
Ma @ index-8646652c.js:40
og @ index-8646652c.js:40
vo @ index-8646652c.js:38
xC @ index-8646652c.js:40
wo @ index-8646652c.js:40
Pw @ index-8646652c.js:40
S @ index-8646652c.js:25
O @ index-8646652c.js:25
index-8646652c.js:59 React Router caught the following error during render RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at xh (index-8646652c.js:84:6147)
    at index-8646652c.js:136:23968
    at Fm (index-8646652c.js:38:19518)
    at Kv (index-8646652c.js:40:1571)
    at Iw (index-8646652c.js:40:45998)
    at _w (index-8646652c.js:40:39763)
    at wC (index-8646652c.js:40:39691)
    at Cu (index-8646652c.js:40:39545)
    at th (index-8646652c.js:40:35913) {componentStack: '\n    at https://accel-webapp-dev.slac.stanford.edu…anford.edu/elog/assets/index-8646652c.js:76:1193)'}
```

**Comment by bisegni** [comment]
whas a bad configuration in the backend for data serialization
