### ISSUE TITLE
attachement strange error

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus-frontend#80]
i see this on the backend log, it came directly by tomcat neither from spring or my code
```
2024-08-13T23:54:49.716Z WARN 1 --- [nio-8080-exec-9] o.apache.coyote.http11.Http11Processor : The HTTP response header [Content-Disposition] with value [inline; filename="Screenshot 2024-08-07 at 11.16.59 AM.png"] has been removed from the response because it is invalid
java.lang.IllegalArgumentException: The Unicode character [ ] at code point [8,239] cannot be encoded as it is outside the permitted range of 0 to 255
at org.apache.tomcat.util.buf.MessageBytes.toBytesSimple(MessageBytes.java:286) ~[tomcat-embed-core-10.1.15.jar!/:na]
at org.apache.tomcat.util.buf.MessageBytes.toBytes(MessageBytes.java:259) ~[tomcat-embed-core-10.1.15.jar!/:na]
```

**Comment by ocboogie** [comment]
@bisegni Is this fixed now?

**Comment by bisegni** [comment]
yes you can close
